# Common compile options applied via karevona_configure_target().
function(karevona_configure_target target)
  if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
    target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic -Wshadow -Wnon-virtual-dtor)
    if(KAREVONA_WERROR)
      target_compile_options(${target} PRIVATE -Werror)
    endif()
    if(KAREVONA_SANITIZE)
      string(REPLACE ";" "," _san "${KAREVONA_SANITIZE}")
      target_compile_options(${target} PRIVATE -fsanitize=${_san} -fno-omit-frame-pointer)
      target_link_options(${target} PRIVATE -fsanitize=${_san})
    endif()
  endif()
endfunction()
